ADA-Cohort4/MC3G15-Morning

README.md

Change on readme.md

---

Rekord/Presentation/Onboarding&Login/SetupPin.swift
Rekord/Resources/Storyboards/Onboarding&Login/SetupPin.storyboard

Setup PIN Page

---

Rekord.xcodeproj/project.pbxproj
Rekord/Core/Entities/TransactionModel.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/TransactionRepository.swift
Rekord/Helpers/CommonFunction.swift
Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Rekord.entitlements
Rekord/Resources/Storyboards/Dashboard/AddTransaction.storyboard

Add Transaction Page

---

Rekord/Core/Repositories/TransactionRepository.swift
Rekord/Core/Repositories/UserRepository.swift
Rekord/Info.plist
Rekord/Presentation/Dashboard/AddTransaction.swift

Update User Repository Snippet

---

Rekord/Core/Entities/BusinessModel.swift
Rekord/Core/Entities/UserModel.swift
Rekord/Core/Networking/Model/UsersModel+Networking.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/BusinessRepository.swift
Rekord/Core/Repositories/UserRepository.swift

User Repo now have saveUser
UpdateUser and DeleteUser to airtable API
Nih yah Tia

add status, enhance user repo

---

Rekord/Core/Networking/BusinessAPIRequest.swift
Rekord/Core/Networking/Model/BusinessModel+Networking.swift
Rekord/Core/Networking/Model/UsersModel+Networking.swift
Rekord/Core/Repositories/BusinessRepository.swift
Rekord/Core/Repositories/TransactionRepository.swift
Rekord/Core/Repositories/UserRepository.swift

adding Airtable on Business Repository,
Tia tolong pull request lagi yah

Business Repository

---

Rekord/Core/Entities/TransactionModel.swift
Rekord/Core/Entities/TransactionStatusType.swift
Rekord/Core/Networking/Model/TransactionsModel+Networking.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/TransactionRepository.swift
Rekord/Presentation/Dashboard/AddTransaction.swift

capabilities for post and patch Airtable,
adding id_business for relate between transactions and business,
change total_price for string into float
tweak addtransaction controller since require id_business and change into float

Transaction Repo

---

Rekord/Resources/Storyboards/Settings&DataSharing/DataSharing.storyboard
Rekord/Resources/Storyboards/Settings&DataSharing/ProfilePage.storyboard

Create Profile and Users List Storyboard

Profile and Users List Storyboard

---

Rekord/Core/Entities/PartnerModel.swift
Rekord/Core/Entities/PartnerType.swift
Rekord/Core/Networking/Model/PartnersModel+Networking.swift
Rekord/Core/Repositories/BusinessRepository.swift
Rekord/Core/Repositories/PartnerRepository.swift
Rekord/Core/Repositories/TransactionRepository.swift

Partner now can add, update and delete from airtable too.
also fixing some issue on Transaction Repository and Business Repository

Partner Repository

---

Rekord/Core/Entities/PaymentModel.swift
Rekord/Core/Networking/Model/PaymentsModel+Networking.swift
Rekord/Core/Repositories/PaymentRepository.swift

Update Payment Repo for insert into airtable too.
Also this is only positive case

Payment Repo

---

Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents

ada yang ketinggalan nama di CoreData Partner

add Name on CoreData

---

Rekord/Core/Networking/BaseRequest.swift
Rekord/Core/Networking/Model/BusinessModel+Networking.swift
Rekord/Core/Repositories/BusinessRepository.swift
Rekord/Core/Repositories/PartnerRepository.swift
Rekord/Helpers/Constant/Constants.swift
Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Presentation/Dashboard/Dashboard.swift
Rekord/Presentation/Dashboard/LockScreen.swift
Rekord/Presentation/Onboarding&Login/ConfirmPinViewController.swift
Rekord/Resources/Storyboards/Dashboard/LockScreen.storyboard
Rekord/Resources/Storyboards/Onboarding&Login/SetupPin.storyboard
Rekord/Resources/Storyboards/rootTabBar.storyboard

create to airtable and login segue

create to airtable and login segue

---

Rekord/Core/Entities/PaymentModel.swift
Rekord/Core/Entities/TransactionModel.swift
Rekord/Core/Networking/Model/PaymentsModel+Networking.swift
Rekord/Core/Networking/Model/TransactionsModel+Networking.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/PaymentRepository.swift
Rekord/Core/Repositories/TransactionRepository.swift

I am already debug and found that my Airtable Model is using String, it's now fixed and sending number (which in AirTable Number means float, double or Int)

Fixing issue on Transaction and Payment

---

Rekord.xcodeproj/project.pbxproj
Rekord/Core/Entities/PartnerModel.swift
Rekord/Core/Entities/PartnerType.swift
Rekord/Core/Networking/Model/BusinessModel+Networking.swift
Rekord/Core/Networking/Model/PartnersModel+Networking.swift
Rekord/Core/Networking/Model/TransactionsModel+Networking.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/BusinessRepository.swift
Rekord/Core/Repositories/PartnerRepository.swift
Rekord/Core/Repositories/TransactionRepository.swift
Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Presentation/Dashboard/Dashboard.swift
Rekord/Presentation/Transaction&History/DatePickerCell.swift
Rekord/Presentation/Transaction&History/FilterView.swift
Rekord/Presentation/Transaction&History/History.swift
Rekord/Resources/Storyboards/Transactions&History/DatePickerCell.xib
Rekord/Resources/Storyboards/Transactions&History/History.storyboard

fixed epic bugs on repositories

Fixed bugs on repositories

---

Rekord/Core/Repositories/UserRepository.swift
Rekord/Presentation/Dashboard/LockScreen.swift
Rekord/Presentation/Onboarding&Login/ConfirmPinViewController.swift
Rekord/Presentation/Onboarding&Login/SetupBusinessViewController.swift
Rekord/Resources/Storyboards/Onboarding&Login/Login.storyboard
Rekord/Resources/Storyboards/Onboarding&Login/SetupPin.storyboard

finish creating business validation for setting up business

Finish business validation

---

Rekord/Presentation/Dashboard/Dashboard.swift
Rekord/Presentation/Transaction&History/History.swift

Finish get all transaction in history page

Finish history get all transaction

---

Rekord.xcodeproj/project.pbxproj
Rekord/Info.plist
Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Presentation/Partner/AddNewPartner.swift
Rekord/Presentation/Partner/EditPartner.swift
Rekord/Presentation/Partner/Partner.swift
Rekord/Presentation/Partner/PartnerDetail.swift
Rekord/Presentation/Transaction&History/TransactionDetails.swift
Rekord/Resources/Storyboards/Partner/Partner.storyboard

Finished create new partner logic, added logic to display partner information when editing partner.

Finished Add New Partner Logic

---

Rekord.xcodeproj/project.pbxproj
Rekord/Info.plist
Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Resources/Storyboards/Dashboard/AddTransaction.storyboard

Fixing Add transaction function

add transaction

---

Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Presentation/Dashboard/Dashboard.swift

-adding view did appear after saving data on Add Transaction
-adding Locale Formatter

Fixing Bugs on Dashboard

---

Rekord/Presentation/Dashboard/AddTransaction.swift
Rekord/Presentation/Partner/AddNewPartner.swift
Rekord/Presentation/Partner/Partner.swift
Rekord/Resources/Storyboards/Partner/Partner.storyboard

Added alert buat nungguin pas save data ke airtable, bugfix update view addpartner

Bugfix for addpartner, added alerts

---

Rekord.xcodeproj/project.pbxproj
Rekord/Info.plist
Rekord/Presentation/Partner/AddNewPartner.swift
Rekord/Presentation/Partner/Partner.swift
Rekord/Resources/Storyboards/Partner/Partner.storyboard

Finished bug fixing based on determined backlog.
- Rounded button for add Partner (empty state)
- Adjusted Save button position
- Removed partner Type cell from add partner form and adjustment on form layout
- Added title on Add Partner navigation
- Completed keyboard dismissal for Add Partner Page
- Added validation for email on add partner

Finished Bug Fixes

---

Rekord/Core/Repositories/PaymentRepository.swift
Rekord/Presentation/Partner/Partner.swift
Rekord/Presentation/Partner/PartnerDetail.swift
Rekord/Presentation/Transaction&History/TransactionDetails.swift
Rekord/Presentation/Transaction&History/UpdateTransaction.swift
Rekord/Resources/Storyboards/Partner/Partner.storyboard
Rekord/Resources/Storyboards/Transactions&History/TransactionDetail.storyboard
Rekord/Resources/Storyboards/Transactions&History/UpdateTransaction.storyboard

update payment dh bisa sama transaction udh bisa difinalized. Added alerts for validation in addTransaction. Also added segue to partner detail (blom ada logic)

added updateTrx / payment logic

---

Rekord.xcodeproj/project.pbxproj
Rekord/Presentation/Partner/AddNewPartner.swift
Rekord/SupportingFiles/Partner Storyboard Cells/SelectFromContactCell.xib

Added select from contact function with validations for certain fields

Completed select from contact function

---

Rekord/Core/Entities/PartnerModel.swift
Rekord/Core/Entities/PartnerType.swift
Rekord/Core/Entities/TransactionModel.swift
Rekord/Core/Entities/TransactionStatusType.swift
Rekord/Core/Networking/Model/PartnersModel+Networking.swift
Rekord/Core/Networking/Model/TransactionsModel+Networking.swift
Rekord/Core/Rekord.xcdatamodeld/Rekord.xcdatamodel/contents
Rekord/Core/Repositories/PartnerRepository.swift
Rekord/Core/Repositories/TransactionRepository.swift

this is update for change on Partner and Transaction Behavior

Change Partner and Transaction behavior

---

Rekord/Presentation/Settings&DataSharing/Settings.swift
Rekord/Resources/Storyboards/Settings&DataSharing/ProfilePage.storyboard

Debug Profile Page

---

Rekord/Presentation/Partner/AddNewPartner.swift
Rekord/Presentation/Partner/EditPartner.swift
Rekord/Resources/Storyboards/Partner/Partner.storyboard
Rekord/Resources/Storyboards/Partner/PartnerDetail.storyboard

- Added constraints on add partner storyboards
- Added constraints on edit partner
- Removed Partner Type cell on edit Partner
- Removed unnecessary code

Added Constraints
